### ISSUE TITLE
Windows / WSL support

### ISSUE THREAD

**Issue by hamvocke** [hamvocke/lnks#1]
Right now, we're not properly supporting Windows or WSL environments. This is mostly blocked by me not having access to a machine with a Windows installation on it.

Getting it working with both, Windows and WSL, should be rather simple since `fzf` is available for Windows and we're not doing much more than orchestrating `fzf`. It's probably a matter of figuring out two things:

1. what's the best `open`/`xdg-open` equivalent to use on WSL to open the user's default browser?
2. do we need a Powershell (`lnks.ps1`) script that's equivalent to the `lnks.sh` script but works more idiomatically on Windows environments?

**Comment by eabase** [comment]
I was just gonna ask. 
This is super cool. 

The cool thing with powershell is that you can click on links in the Windows Terminal to open them.
(All you need is a valid URL inside the window and it's clickable.)

Also, since `fzf` works great in MSYS/Cygwin, you can open links directly in browser from command line. 

**Cygwin**:  
`cygstart https://github.com/hamvocke/lnks/`

**MSYS MinGW/UCRT64**  
`start https://github.com/hamvocke/lnks/`
